version: '2'

services:
  jenkins: 
    build: .
    image: zojeda/jenkins-docker-cd
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9090:8080"
    environment:
      - DOCKER_API_VERSION=1.22
 